nome = str(input("Digite seu nome completo: ")).strip()
print("Analizando seu nome...")
print("Seu nome em maiúsculas é {}".format(nome.upper()))
print("Seu nome em minúsculas é {}".format(nome.lower()))
snome = nome.split()
print("Possui {} letras".format(len(nome)-nome.count(' ')))
print("O primeiro nome tem {} letras.".format(len(snome[0])))
